_target_: armlet.audit.audit_model_from_results_json

exp_dir: audit/testt

metrics_type_to_audit:
  global: True
  locals: True
  prefit: True
  postfit: True

last_n_rounds: 20
agg_func: mean

utility_metrics:

  accuracy:
    objective: above
    threshold: 80

  recall:
    objective: above
    threshold: 90

  test:
    objective: below
    threshold: 50

fairness_metrics:

  age_eod:
    objective: below
    threshold: 5

  gender_eod:
    objective: below
    threshold: 50

cost_metrics:
  test:
    objective: below
    threshold: 50

privacy_metrics:
  test:
    objective: below
    threshold: 50
