# @package method.hyperparameters

defaults:
  - default.yaml

model:
  _target_: armlet.utils.net.MLP
  n_hidden_layer_1: 64
  n_hidden_layer_2: 32

client:
  loss: 
    _target_: torch.nn.BCEWithLogitsLoss
